# Generated by Django 4.2.16 on 2024-10-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('nusp', models.IntegerField()),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.docente')),
            ],
        ),
    ]
