# Generated by Django 4.2.16 on 2024-10-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientandos', to='relatorios.docente'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField()),
                ('nro_tentativa', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Vazio'), (1, 'Preenchido'), (2, 'Avaliado Por Docente'), (3, 'Avaliado Por Ccp')])),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='relatorios.aluno')),
                ('docente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to='relatorios.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.CharField(max_length=255)),
                ('conceito', models.IntegerField(choices=[(0, 'Adequado'), (1, 'Adequado Com Ressalvas'), (2, 'Insatisfatorio')])),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='relatorios.docente')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='relatorios.relatorio')),
            ],
        ),
    ]
