# Generated by Django 4.2.16 on 2024-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_alter_aluno_orientador_relatorio_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='atividades_academicas',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='atividades_pesquisa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='nro_artigos_aceitos',
            field=models.IntegerField(null=True),
        ),
    ]
